/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestion.pkg;

import static Gestion.pkg.SpectaclesDisponibles.connection;
import java.awt.Component;
import java.io.File;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import oracle.jdbc.OracleTypes;

class ComboItem
{
    private String key;
    private long value;

    public ComboItem(String key, long value)
    {
        this.key = key;
        this.value = value;
    }

    @Override
    public String toString()
    {
        return key;
    }

    public String getKey()
    {
        return key;
    }

    public long getValue()
    {
        return value;
    }
}
public class GestionSpectacles extends javax.swing.JFrame {
    public static Connection connection;
    ResultSet rset,rsetCategorie;
    public JFileChooser chooser=null;
    /**
     * Creates new form GestionSpectacles
     * @param conn
     */
    public GestionSpectacles(Connection conn) {
        initComponents();
        connection = conn;
        String sql1 = "SELECT NUMSPECTACLE, NOMSPECTACLE, NOMCATEGORIE, ARTISTESPECTACLE, AFFICHESPECTACLE FROM SPECTACLES SP" +
                     " INNER JOIN CATEGORIES_SPECTACLE CS ON SP.NUMCATEGORIE=CS.NUMCATEGORIE Order by SP.NUMSPECTACLE";
        try {
            Statement stm = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rset = stm.executeQuery(sql1);
            rset.next();
            AfficherSpectacle();
            
            CallableStatement stm2 = connection.prepareCall("{ ? = call GESTION.AFFICHERCATEGORIES()}");
            stm2.registerOutParameter(1, OracleTypes.CURSOR);
            stm2.execute(); //execution de la fonction
            // Caster le paramètre de retour en ResultSet
            rsetCategorie = (ResultSet) stm2.getObject(1);
           
            while(rsetCategorie.next())
            {
                CB_Categories.addItem(new ComboItem(rsetCategorie.getString(2), rsetCategorie.getLong(1)));
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
    public void AfficherSpectacle()
    {
        try{
            TB_Numero.setText(Long.toString(rset.getLong(1)));
            TB_Nom.setText(rset.getString(2));
            LB_Artiste.setText(rset.getString(3));
            //CB_Categories.setText(rset.getString(4));
        }
        catch(SQLException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTN_Ajouter = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BTN_Modifier = new javax.swing.JButton();
        BTN_Supprimer = new javax.swing.JButton();
        BTN_Vider = new javax.swing.JButton();
        BTN_Dernier = new javax.swing.JButton();
        BTN_Suivant = new javax.swing.JButton();
        BTN_Precedent = new javax.swing.JButton();
        BTN_Premier = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TB_Numero = new javax.swing.JTextField();
        TB_Nom = new javax.swing.JTextField();
        LB_Artiste = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        IMG_AfficheSpectacle = new javax.swing.JLabel();
        BTN_ChoisirPhoto = new javax.swing.JButton();
        CB_Categories = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion spectacles");

        BTN_Ajouter.setText("Ajouter");
        BTN_Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AjouterActionPerformed(evt);
            }
        });

        jButton2.setText("Quitter");

        BTN_Modifier.setText("Modifier");

        BTN_Supprimer.setText("Supprimer");
        BTN_Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SupprimerActionPerformed(evt);
            }
        });

        BTN_Vider.setText("Vider");
        BTN_Vider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ViderActionPerformed(evt);
            }
        });

        BTN_Dernier.setText("Dernier");
        BTN_Dernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DernierActionPerformed(evt);
            }
        });

        BTN_Suivant.setText(">>");
        BTN_Suivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SuivantActionPerformed(evt);
            }
        });

        BTN_Precedent.setText("<<");
        BTN_Precedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PrecedentActionPerformed(evt);
            }
        });

        BTN_Premier.setText("Premier");
        BTN_Premier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PremierActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom");

        jLabel2.setText("Artiste");

        jLabel3.setText("Numéro");

        jLabel4.setText("Catégorie");

        TB_Numero.setEnabled(false);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setToolTipText("");

        IMG_AfficheSpectacle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gestion/pkg/Images/png_dessin342_titom_picto_couleurs_papiers_spectacle.png"))); // NOI18N

        BTN_ChoisirPhoto.setText("Choisir une photo");
        BTN_ChoisirPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ChoisirPhotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TB_Nom, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(TB_Numero, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(LB_Artiste, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(CB_Categories, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IMG_AfficheSpectacle, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTN_ChoisirPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTN_Premier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_Vider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTN_Ajouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_Precedent, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTN_Modifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_Suivant, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_Supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_Dernier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TB_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TB_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(LB_Artiste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(CB_Categories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(IMG_AfficheSpectacle, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTN_ChoisirPhoto)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Dernier)
                    .addComponent(BTN_Suivant)
                    .addComponent(BTN_Precedent)
                    .addComponent(BTN_Premier))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Modifier)
                    .addComponent(BTN_Ajouter)
                    .addComponent(BTN_Supprimer)
                    .addComponent(BTN_Vider))
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addContainerGap())
        );

        BTN_Ajouter.getAccessibleContext().setAccessibleName("BTN_Ajouter");
        jButton2.getAccessibleContext().setAccessibleName("BTN_Quitter");
        BTN_Modifier.getAccessibleContext().setAccessibleName("BTN_Modifier");
        BTN_Supprimer.getAccessibleContext().setAccessibleName("BTN_Supprimer");
        BTN_Vider.getAccessibleContext().setAccessibleName("BTN_Vider");
        BTN_Dernier.getAccessibleContext().setAccessibleName("BTN_Dernier");
        BTN_Suivant.getAccessibleContext().setAccessibleName("BTN_Suivant");
        BTN_Precedent.getAccessibleContext().setAccessibleName("BTN_Precedent");
        BTN_Premier.getAccessibleContext().setAccessibleName("BTN_Premier");
        jLabel1.getAccessibleContext().setAccessibleName("LB_Nom");
        jLabel2.getAccessibleContext().setAccessibleName("LB_Artiste");
        jLabel3.getAccessibleContext().setAccessibleName("LB_Numero");
        jLabel4.getAccessibleContext().setAccessibleName("LB_Categorie");
        TB_Numero.getAccessibleContext().setAccessibleName("TB_Numero");
        TB_Nom.getAccessibleContext().setAccessibleName("TB_Nom");
        LB_Artiste.getAccessibleContext().setAccessibleName("LB_Artiste");
        IMG_AfficheSpectacle.getAccessibleContext().setAccessibleName("IMG_AfficheSpectacle");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_ChoisirPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ChoisirPhotoActionPerformed
        chooser = new JFileChooser(System.getProperty("user.dir") + "\\src\\Gestion\\pkg\\Images");
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
        "JPG & GIF Images", "jpg", "gif", "jpeg", "png", "bmp");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            IMG_AfficheSpectacle.setIcon(new ImageIcon(chooser.getSelectedFile().getPath()));
            IMG_AfficheSpectacle.setSize(200,200);
        }
    }//GEN-LAST:event_BTN_ChoisirPhotoActionPerformed

    private void BTN_PremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PremierActionPerformed
        try {
            rset.first();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        AfficherSpectacle();
    }//GEN-LAST:event_BTN_PremierActionPerformed

    private void BTN_DernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DernierActionPerformed
        try {
            rset.last();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        AfficherSpectacle();
    }//GEN-LAST:event_BTN_DernierActionPerformed

    private void BTN_PrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PrecedentActionPerformed
        try{
            if(rset.previous())
                AfficherSpectacle();
        }catch (SQLException ex){
            System.out.println(ex.getMessage());
        }
        AfficherSpectacle();  
    }//GEN-LAST:event_BTN_PrecedentActionPerformed

    private void BTN_SuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SuivantActionPerformed
        try{
            if(rset.next())
                AfficherSpectacle();
        }catch (SQLException ex){
            System.out.println(ex.getMessage());
        }
        AfficherSpectacle(); 
    }//GEN-LAST:event_BTN_SuivantActionPerformed

    private void BTN_ViderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ViderActionPerformed
        TB_Numero.setText("");
        TB_Nom.setText("");
        LB_Artiste.setText("");
        //CB_Categories.setText("");
    }//GEN-LAST:event_BTN_ViderActionPerformed

    private void BTN_AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AjouterActionPerformed
                try {
                    TB_Numero.setText("");
                    CallableStatement stm = connection.prepareCall("{call GESTION.AJOUTERSPECTACLE(?,?,?,?)}");
                    stm.setString(1, TB_Nom.getText());
                    stm.setString(2, LB_Artiste.getText());
                    stm.setLong(3, CB_Categories.getSelectedIndex()+1);
                    if(chooser != null)
                        stm.setString(4, chooser.getSelectedFile().getPath());
                    else
                        stm.setString(4, IMG_AfficheSpectacle.getIcon().toString());
                    stm.execute(); //execution de la fonction
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
    }//GEN-LAST:event_BTN_AjouterActionPerformed

    private void BTN_SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SupprimerActionPerformed
                try {
                    CallableStatement stm = connection.prepareCall("{call GESTION.SUPPRIMERSPECTACLE(?)}");
                    stm.setString(1, TB_Numero.getText());
                    stm.execute(); //execution de la fonction
                    rset.beforeFirst();;
                    AfficherSpectacle();
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
    }//GEN-LAST:event_BTN_SupprimerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionSpectacles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionSpectacles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionSpectacles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionSpectacles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GestionSpectacles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Ajouter;
    private javax.swing.JButton BTN_ChoisirPhoto;
    private javax.swing.JButton BTN_Dernier;
    private javax.swing.JButton BTN_Modifier;
    private javax.swing.JButton BTN_Precedent;
    private javax.swing.JButton BTN_Premier;
    private javax.swing.JButton BTN_Suivant;
    private javax.swing.JButton BTN_Supprimer;
    private javax.swing.JButton BTN_Vider;
    private javax.swing.JComboBox CB_Categories;
    private javax.swing.JLabel IMG_AfficheSpectacle;
    private javax.swing.JTextField LB_Artiste;
    private javax.swing.JTextField TB_Nom;
    private javax.swing.JTextField TB_Numero;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
