/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestion.pkg;

import static Gestion.pkg.SpectaclesDisponibles.connection;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author Emmanuel
 */
public class Livraison extends javax.swing.JFrame {
    public static Connection connection;
    ResultSet rset;
    /**
     * Creates new form Livraison
     * @param conn
     */
    public Livraison(Connection conn) {
        initComponents();
        connection = conn;
        String sql1 = "SELECT NUMCLIENT, NOMCOMPLET, NOMUSAGER, ADRESSECLIENT, NUMTELCLIENT FROM CLIENTS WHERE NUMCLIENT IN(SELECT NUMCLIENT FROM FACTURE)";
        try {
            Statement stm = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            //stm.registerOutParameter(1, OracleTypes.CURSOR);
            //stm.execute; //execution de la fonction
            // Caster le paramètre de retour en ResultSet
            //rset = (ResultSet) stm.getObject(1);
            rset = stm.executeQuery(sql1);
            rset.next();
            AfficherUsager();
            
            //CallableStatement stm = connection.prepareCall("{ ? = call GESTION.AFFICHERSPECTACLESRESTANTS()}");
            //stm.registerOutParameter(1, OracleTypes.CURSOR);
            //stm.execute(); //execution de la fonction
            // Caster le paramètre de retour en ResultSet
            //rset = (ResultSet) stm.getObject(1);
            
            
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
    public void AfficherUsager()
    {
        try{
            TB_Num.setText(Long.toString(rset.getLong(1)));
            TB_Nom.setText(rset.getString(2));
            TB_Usager.setText(rset.getString(3));
            TB_Adresse.setText(rset.getString(4));
            TB_NumTel.setText(rset.getString(5));
        }
        catch(SQLException ex)
        {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTN_Suivant = new javax.swing.JButton();
        TB_Adresse = new javax.swing.JTextField();
        BTN_Precedant = new javax.swing.JButton();
        BTN_Premier = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TB_Num = new javax.swing.JTextField();
        TB_Nom = new javax.swing.JTextField();
        BTN_Dernier = new javax.swing.JButton();
        TB_Usager = new javax.swing.JTextField();
        TB_NumTel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informations client");
        setResizable(false);

        BTN_Suivant.setText(">>");
        BTN_Suivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SuivantActionPerformed(evt);
            }
        });

        TB_Adresse.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TB_Adresse.setEnabled(false);

        BTN_Precedant.setText("<<");
        BTN_Precedant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PrecedantActionPerformed(evt);
            }
        });

        BTN_Premier.setText("Premier");
        BTN_Premier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PremierActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom complet");

        jLabel2.setText("Nom usager");

        jButton2.setText("Quitter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Numéro");

        jLabel4.setText("Adresse");

        TB_Num.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TB_Num.setEnabled(false);

        TB_Nom.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TB_Nom.setEnabled(false);

        BTN_Dernier.setText("Dernier");
        BTN_Dernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DernierActionPerformed(evt);
            }
        });

        TB_Usager.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TB_Usager.setEnabled(false);

        TB_NumTel.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TB_NumTel.setEnabled(false);

        jLabel6.setText("Num. Tel.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(45, 45, 45))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TB_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TB_Usager, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TB_Adresse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(TB_NumTel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TB_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(231, 231, 231))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_Premier)
                        .addGap(28, 28, 28)
                        .addComponent(BTN_Precedant, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_Suivant, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(BTN_Dernier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TB_Num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TB_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TB_Usager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TB_Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TB_NumTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Dernier)
                    .addComponent(BTN_Suivant)
                    .addComponent(BTN_Precedant)
                    .addComponent(BTN_Premier)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        TB_Adresse.getAccessibleContext().setAccessibleName("TB_Adresse");
        jLabel1.getAccessibleContext().setAccessibleName("LB_Fullname");
        jLabel2.getAccessibleContext().setAccessibleName("LB_Username");
        jLabel4.getAccessibleContext().setAccessibleName("LB_Adresse");
        TB_Nom.getAccessibleContext().setAccessibleName("TB_Fullname");
        TB_Usager.getAccessibleContext().setAccessibleName("TB_Username");
        TB_NumTel.getAccessibleContext().setAccessibleName("TB_Tel");
        jLabel6.getAccessibleContext().setAccessibleName("LB_Tel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_PremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PremierActionPerformed
        try {
            rset.first();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        AfficherUsager();
    }//GEN-LAST:event_BTN_PremierActionPerformed

    private void BTN_DernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DernierActionPerformed
        try{
            rset.last();
        }catch (SQLException ex){
            System.out.println(ex.getMessage());
        }
        AfficherUsager();
    }//GEN-LAST:event_BTN_DernierActionPerformed

    private void BTN_PrecedantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PrecedantActionPerformed
        try{
            if(!rset.isFirst())
            {
                rset.previous();
                AfficherUsager();
            }
        }catch (SQLException ex){
            System.out.println(ex.getMessage());
        }
        AfficherUsager();        
    }//GEN-LAST:event_BTN_PrecedantActionPerformed

    private void BTN_SuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SuivantActionPerformed
        try{
            if(!rset.isLast())
            {
                rset.next();
                AfficherUsager();
            }
        }catch (SQLException ex){
            System.out.println(ex.getMessage());
        }
        AfficherUsager(); 
    }//GEN-LAST:event_BTN_SuivantActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Livraison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Livraison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Livraison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Livraison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Livraison().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Dernier;
    private javax.swing.JButton BTN_Precedant;
    private javax.swing.JButton BTN_Premier;
    private javax.swing.JButton BTN_Suivant;
    private javax.swing.JTextField TB_Adresse;
    private javax.swing.JTextField TB_Nom;
    private javax.swing.JTextField TB_Num;
    private javax.swing.JTextField TB_NumTel;
    private javax.swing.JTextField TB_Usager;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
